language: java
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/

script:
    - ./gradlew check shadowJar

after_success:
    - java -jar build/libs/JavaDagger-1.0.jar

after_script:
    - ./gradlew jacocoTestReport coveralls
