language: java
sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/

script:
    - ./gradlew check jacocoTestReport coveralls shadowJar

after_script:
    - java -jar build/libs/JavaDagger-1.0.jar